version: 0.0
os: linux
files:
  - source: ./app
    destination: /home/ec2-home/
  - source: ./etc/init/transcribe-tech-talks.conf 
    destination: /etc/init/

hooks:
  BeforeInstall:
    - location: codedeploy/remove_previous_install.sh
      timeout: 30
  ApplicationStop:
    - location: codedeploy/stop_server.sh
      timeout: 30
  ApplicationStart:
    - location: codedeploy/start_server.sh
      timeout: 30
